version: '3'
services:
  api:
    build:
      context: backend
      dockerfile: Dockerfile
    env_file: .env 
    ports:
      - 5000:5000
    expose:
      - 5000
    environment:
      - PYTHONUNBUFFERED=1
    restart: always
    platform: linux/amd64

